### ISSUE TITLE
向大佬请教关于“PermissionError: [WinError 5] 拒绝访问”报错的解决方式

### ISSUE THREAD

**Issue by koalaaaaaaaaa** [Milloyy/ZhihuSpider#1]
大佬你好，我知道你博士期间学业繁忙，但在网上查询解决方式无果后，又不甘心就此放弃，只好来打扰你。如果你能够忙里抽空解决下我的问题，我将十分感激。
在运行你在readme.md中给出的示例代码：
zhihu -u https://www.zhihu.com/question/371430700
时，弹出了：
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\Milloy'
的报错。
我翻阅电脑的文件目录发现，C:\\Users 文件夹下没有 Milloy 这个文件（文件夹），因此感到十分茫然，请大佬指教
![批注 2020-02-22 132212](https://user-images.githubusercontent.com/59307253/75087047-6fe4f800-5576-11ea-8750-47c7a936f180.png)

**Comment by koalaaaaaaaaa** [comment]
看到你的用户名，我好像有些明白问题出在哪里了
请问大佬，我要如何修改我上面提的问题里的涉及到的那个文件路径呢

**Comment by Milloyy** [comment]
返回默认路径时会优先查找config.py文件下的“running/default_wh"路径，如果不为空就会直接返回，否则程序会临时生成默认路径。查看了一下源代码，发现“running/default_wh"不知何时存储了我的默认路径，将这个默认路径删除就可以了。

**Comment by Milloyy** [comment]
config.py中的代码由config_tool.py生成，在生成过程中存储了我的默认路径，现在已经修复了这个bug。PermissionError应该是程序没有权限生成”C:\Users\Milloy“这个文件夹。

**Comment by koalaaaaaaaaa** [comment]
谢谢大佬！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"蘑菇汤"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 上午8:47
收件人:&nbsp;"Milloyy/ZhihuSpider"<ZhihuSpider@noreply.github.com&gt;;
抄送:&nbsp;"1595022729"<1595022729@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Milloyy/ZhihuSpider] 向大佬请教关于“PermissionError: [WinError 5] 拒绝访问”报错的解决方式 (#1)




config.py中的代码由config_tool.py生成，在生成过程中存储了我的默认路径，现在已经修复了这个bug。PermissionError应该是程序没有权限生成”C:\Users\Milloy“这个文件夹。
