### ISSUE TITLE
当一个问题下的答案数太多时，只能爬取2%的回答么？

### ISSUE THREAD

**Issue by Ga091an** [Milloyy/ZhihuSpider#12]

**Comment by Milloyy** [comment]
可以在源代码中自己修改爬取比例。

**Comment by jacklanda** [comment]
> 可以在源代码中自己修改爬取比例。

你好，我想一个问题下的全部回答，应该在哪个源文件里进行修改呢？谢谢～（找了好一会，没找出来....）

**Comment by jacklanda** [comment]
> > 可以在源代码中自己修改爬取比例。
> 
> 你好，我想下载一个问题下的全部回答，应该在哪个源文件里进行修改呢？谢谢～（找了好一会，没找出来....）

是要改management.py文件下的self.totals吗？我是了一下，不奏效呢

**Comment by Ga091an** [comment]
> > > 可以在源代码中自己修改爬取比例。
> > 
> > 
> > 你好，我想下载一个问题下的全部回答，应该在哪个源文件里进行修改呢？谢谢～（找了好一会，没找出来....）
> 
> 是要改management.py文件下的self.totals吗？我是了一下，不奏效呢

改0.02试试

**Comment by jacklanda** [comment]
> > > > 可以在源代码中自己修改爬取比例。
> > > 
> > > 
> > > 你好，我想下载一个问题下的全部回答，应该在哪个源文件里进行修改呢？谢谢～（找了好一会，没找出来....）
> > 
> > 
> > 是要改management.py文件下的self.totals吗？我是了一下，不奏效呢
> 
> 改0.02试试

我已经解决问题了，问题不在于我修改的地方，因为我改对了地方，原因是自己很粗心，使用的时候用的 后接url不对，谢谢了～
