### ISSUE TITLE
你好，我想下载一个问题下的全部回答，应该在哪个源文件里进行修改呢？谢谢～（找了好一会，没找出来....）

### ISSUE THREAD

**Issue by jacklanda** [Milloyy/ZhihuSpider#18]

**Comment by Milloyy** [comment]
`zhihu -> spider -> management.py -> QuestionManagement.__init__ -> init_totals_title`
把`init_totals_title`函数的下面部分
```
if totals <= 20:
    s.totals = totals
elif totals <= 1000:
    s.totals = 20
else:
    s.totals = int(totals * 0.02)
```
改成：

```
s.totals = totals
```

就可以了。

**Comment by jacklanda** [comment]
> `zhihu -> spider -> management.py -> QuestionManagement.__init__ -> init_totals_title`
> 把`init_totals_title`函数的下面部分
> 
> ```
> if totals <= 20:
>     s.totals = totals
> elif totals <= 1000:
>     s.totals = 20
> else:
>     s.totals = int(totals * 0.02)
> ```
> 
> 改成：
> 
> ```
> s.totals = totals
> ```
> 
> 就可以了。
你好，很奇怪呢，我改后的代码如下：
![图片](https://user-images.githubusercontent.com/54089835/100598435-ad628700-3339-11eb-9aa6-82a712167d96.png)
不知道为什么，还是只能下载一个问题下的最高票答案.......不知道是不是还遗漏了什么步骤呢。
![图片](https://user-images.githubusercontent.com/54089835/100598756-21049400-333a-11eb-8bea-bdfff6725f54.png)

**Comment by Milloyy** [comment]
你给程序输入的链接不对，要爬取整个问题答案得用：https...question/xxxx 形式的链接。xxxx是Question ID，是数字。

**Comment by jacklanda** [comment]
> 你给程序输入的链接不对，要爬取整个问题答案得用：https...question/xxxx 形式的链接。xxxx是Question ID，是数字。

问题解决了，谢谢！
