### ISSUE TITLE
用不了呀，请问你在其他电脑上测试过吗？

### ISSUE THREAD

**Issue by luosaidage** [Milloyy/ZhihuSpider#2]
In [4]: zhihu
Out[4]: <module 'zhihu' from 'C:\\Users\\luosa\\OneDrive\\桌面\\fsdownload\\Zhih
uSpider\\zhihu\\__init__.py'>
In [5]:

运行就报错。

**Comment by Milloyy** [comment]
能提供更详细的信息吗？不确定这种情况问题出在哪里。如果是没有安装，可以用powershell或cmd打开setup.py所在的目录，使用`pyhon setup.py install`命令安装，安装成功后使用`pip list`命令可以看到**zhihu-spider       6.0**。

**Comment by luosaidage** [comment]
PS C:\Users\luosa\OneDrive\桌面\fsdownload\ZhihuSpider> python .\setup.py
C:\Users\luosa\AppData\Local\Programs\Python\Python37\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'keyword'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
PS C:\Users\luosa\OneDrive\桌面\fsdownload\ZhihuSpider>

我用powershell在目录中试了，还是不行。帮忙看看，谢谢。

**Comment by Milloyy** [comment]
你使用的安装命令不全，打开setup.py所在的目录后直接使用“python setup.py install"命令，可以下载一下最新的源代码，今天修复了一些bug。
