### ISSUE TITLE
关于下载回答的比例问题

### ISSUE THREAD

**Issue by taseikyo** [Milloyy/ZhihuSpider#20]
正如 #18 中提到的
有人可能想保存全部回答，目前是仅保存点赞数前 2% 的回答，其实有些低赞回答质量也蛮高的
是否可以加一个参数（比如 --ratio）表示想要保存回答的百分比，比如 --ratio 80 表示想保存前 80%

**Comment by Milloyy** [comment]
我觉得没有必要，保存太多也没用，几百几千甚至几万个答案根本看不完，要大量浏览直接在知乎看就好了。知乎的优质答案大概就1.5%到3%，保存2%基本囊括了所有优质答案。

既然有需要，下次更新会考虑添加这个功能，不过可能会限制同时下载图片。
