### ISSUE TITLE
求助：关于401网络错误的解决方法

### ISSUE THREAD

**Issue by koalaaaaaaaaa** [Milloyy/ZhihuSpider#4]
学长好，有空闲时间的话可以帮忙解决下这个问题嘛？
问题如下：
我在使用学长提供的样例网址时可以顺利爬取数据，但我更换了另一个网址后，出现了401网络错误的问题…
![批注 2020-02-27 185808](https://user-images.githubusercontent.com/59307253/75438701-64893680-5993-11ea-8ace-c6c830a5286c.png)
请问要如何解决呢？

**Comment by Milloyy** [comment]
爬取单个答案时会出现这个问题，应该是触发了知乎的反爬虫，可能需要cookie。过几天再试试。

**Comment by koalaaaaaaaaa** [comment]
好滴～------------------ 原始邮件 ------------------
发件人: "蘑菇汤"<notifications@github.com>
发送时间: 2020年2月28日(星期五) 晚上8:14
收件人: "Milloyy/ZhihuSpider"<ZhihuSpider@noreply.github.com>;
抄送: "koalaaaaaaaaa"<1595022729@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Milloyy/ZhihuSpider] 求助：关于401网络错误的解决方法 (#4)



爬取单个答案时会出现这个问题，应该是触发了知乎的反爬虫，可能需要cookie。过几天再试试。
 
&mdash;
