### ISSUE TITLE
请问为何mac系统下为何无法保存文件？

### ISSUE THREAD

**Issue by ywwang0** [Milloyy/ZhihuSpider#5]
程序运行后输出：
“保存目录：/Users/wangyaowei/Documents\zhihuSpider”
MAC系统下电脑中Document下没有“\zhihuSpider”这一目录，无法找到保存的文件

本人刚接触python不久，尝试了之后没有找到源码中关于保存路径的段落，希望作者有时间帮忙回复，谢谢。

**Comment by koalaaaaaaaaa** [comment]
你有没发现最后一条斜杠反了…



---原始邮件---
发件人: "Yaowei Wang"<notifications@github.com&gt;
发送时间: 2020年3月16日(周一) 下午3:18
收件人: "Milloyy/ZhihuSpider"<ZhihuSpider@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Milloyy/ZhihuSpider] 请问为何mac系统下为何无法保存文件？ (#5)




 
程序运行后输出：
 “保存目录：/Users/wangyaowei/Documents\zhihuSpider”
 MAC系统下电脑中Documents没有这一目录，无法找到保存的文件

**Comment by Milloyy** [comment]
`zhihuSpider`文件夹 没有创建，已经在`zhihu/conf/__init__.py`文件中修复了这个bug。
